### ISSUE TITLE
Can't install v1

### ISSUE THREAD

**Issue by aaccioly** [pirackr/asdf-telepresence#2]
The plug-in can't currently install version `0.109`  despite the fact that its listed.

```bash
 asdf install telepresence 0.109
```

Fails silently.

I assume that the problem is in the download url https://github.com/pirackr/asdf-telepresence/blob/main/bin/install#L45.

https://app.getambassador.io/download/tel2/linux/amd64/2.0.0/telepresence exists
https://app.getambassador.io/download/tel2/linux/amd64/0.109/telepresence don't. 

Unfortunately I don't know what the right url for v1 is..

**Comment by morgoth** [comment]
The installation fails for me as well:
```
wojtek@arda:~$ asdf install telepresence v2.10.5
wojtek@arda:~$ asdf list telepresence
  No versions installed
```

**Comment by pirackr** [comment]
The plugin was broken for a while. I fixed and have an updated version of list-all. It now supports only "releases" versions, not all tags, but should work now.
